[package]
name = "wsp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
rand = "0.8.4"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }